name: Jonathan kemp
favicon: null
layout_spectrum: 0.10546350991353393
typography_spectrum: 0.2511552826035768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.17444785963743925
  lightness: 0.09636808047071099
  saturation: 0.6818913973402232
  rhythmicContrast: 0.9101847300771624
purpose: []
